name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macOS-latest
    env:
      SCHEME: HandyRouter-Package
      CODECOV_PACKAGE_NAME: HandyRouter
    strategy:
      matrix:
        env:
          - sdk: iphonesimulator
            destination: platform=iOS Simulator,name=iPhone 13 Pro,OS=latest

    steps:
      - uses: actions/checkout@v3

      - name: List SDKs and Devices
        run: xcodebuild -showsdks; xcrun xctrace list devices

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build and Test
        run: |
          set -o pipefail
          xcodebuild -resolvePackageDependencies
          xcodebuild clean build test \
            -scheme "$SCHEME" \
            -sdk "$SDK" \
            -destination "$DESTINATION" \
            -configuration Debug \
            -enableCodeCoverage YES \
            -resultBundlePath "./${{ matrix.env.sdk }}.xcresult" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
        env:
          SDK: ${{ matrix.env.sdk }}
          DESTINATION: ${{ matrix.env.destination }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          xcode: true
          xcode_archive_path: "./${{ matrix.env.sdk }}.xcresult"
